// AJAX
export const GET_GIFS = 'GET_GIFS'
export const ADD_GIFS = 'ADD_GIFS'
export const SEARCH_TRENDING_GIFS = 'SEARCH_TRENDING_GIFS'
export const SET_GIFS_OFFSET = 'SET_GIFS_OFFSET'
export const OFFSET_TO_ZERO = 'OFFSET_TO_ZERO'
export const EMPTY_GIFS_ARRAY = 'EMPTY_GIFS_ARRAY'
export const REMOVE_ERROR = 'REMOVE_ERROR'

// AJAX LOADING STATE
export const SET_LOADING_GIFS = 'SET_LOADING_GIFS'
export const SET_LOADED_GIFS = 'SET_LOADED_GIFS'
export const SET_LOADING_MORE_GIFS = 'SET_LOADING_MORE_GIFS'
export const SET_ERROR_ON_LOAD = 'SET_ERROR_ON_LOAD'

// SEARCH
export const TOGGLE_SEARCH_STATE = 'TOGGLE_SEARCH_STATE'
export const SEARCH_STATE_TO_FALSE = 'SEARCH_STATE_TO_FALSE'
export const SEARCH_RETURN_NULL = 'SEARCH_RETURN_NULL'
export const REMOVE_SEARCH_RETURN_TO_NULL = 'REMOVE_SEARCH_RETURN_TO_NULL'
